name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ##### Specify AWS Region #####

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: arh-github-actions
          template: bucket.yaml

  resilience-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install boto
        run: |
          pip install boto3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ##### Specify AWS Region #####
      - name: Resilience check
        env:
          StackARN: ##### Specify CloudFormation stack ARN #####
          AppARN: ##### Specify application ARN on Resilience Hub #####
        run: |
          python .github/scripts/resilience-check.py
          